

export const    PERUCAS: any[] = [

    //Perucas Cacheadas
    {
        id: 0,
        titulo: "Cabelo Mania",
        iconUrl: "https://assets-global.website-files.com/65a7d1096fb2fb72ed44a291/65ae2e95cb9e532608ca93c5_cacheada3.png",
        descricao: "P. Wig Futura Lisa Curta Uso Diário Castanho Escuro Tamanho...",
        preco: "95000.06",
        categoria: 'cacheada',
        fullDescricao: "Aparência super natural; sem dor e não parece peruca; Fácil aplicação; touca aberta de 35 cm; Fibra futura; elástico de ajuste; leve e macia; Suporta calor de secador e chapinha até 180 graus c",
        quantidade: 60,
        marca: "Hass Hair",
        genero: "feminino",
    },
    {
        id: 1,
        titulo: "Black Beauty",
        iconUrl: "https://assets-global.website-files.com/65a7d1096fb2fb72ed44a291/65ae30b6c404c7659500d8f2_cacheada1.png",
        descricao: "P. Wig Futura Lisa Curta Uso Diário Castanho Escuro Tamanho...",
        preco: "10230.00",
        categoria: 'cacheada',
        fullDescricao: "Aparência super natural; sem dor e não parece peruca; Fácil aplicação; touca aberta de 35 cm; Fibra futura; elástico de ajuste; leve e macia; Suporta calor de secador e chapinha até 180 graus c",
        quantidade: 610,
        marca: "Hass Hair",
        genero: "feminino",
    },
    {
        id: 2,
        titulo: "Leny Hair",
        iconUrl: "https://assets-global.website-files.com/65a7d1096fb2fb72ed44a291/65ae30b6c404c7659500d8f2_cacheada1.png",
        descricao: "P. Wig Futura Lisa Curta Uso Diário Castanho Escuro Tamanho...",
        preco: "25670.80",
        categoria: 'cacheada',
        fullDescricao: "Aparência super natural; sem dor e não parece peruca; Fácil aplicação; touca aberta de 35 cm; Fibra futura; elástico de ajuste; leve e macia; Suporta calor de secador e chapinha até 180 graus c",
        quantidade: 96,
        marca: "Hass Hair",
        genero: "feminino",
    },
    {
        id: 3,
        titulo: "Cabelo Mania",
        iconUrl: "https://assets-global.website-files.com/65a7d1096fb2fb72ed44a291/65ae2e95cb9e532608ca93c5_cacheada3.png",
        descricao: "P. Wig Futura Lisa Curta Uso Diário Castanho Escuro Tamanho...",
        preco: "89900.00",
        categoria: 'cacheada',
        fullDescricao: "Aparência super natural; sem dor e não parece peruca; Fácil aplicação; touca aberta de 35 cm; Fibra futura; elástico de ajuste; leve e macia; Suporta calor de secador e chapinha até 180 graus c",
        quantidade: 60,
        marca: "Hass Hair",
        genero: "feminino",
    },

    //Perucas Onduladas

    {
        id: 4,
        titulo: "Fashion Line",
        iconUrl: "https://assets-global.website-files.com/65a7d1096fb2fb72ed44a291/65ae37de852f80447e78faf7_onda1.png",
        descricao: "P. Wig Futura Lisa Curta Uso Diário Castanho Escuro Tamanho...",
        preco: "34098.65",
        categoria: 'ondulada',
        fullDescricao: "Aparência super natural; sem dor e não parece peruca; Fácil aplicação; touca aberta de 35 cm; Fibra futura; elástico de ajuste; leve e macia; Suporta calor de secador e chapinha até 180 graus c",
        quantidade: 60,
        marca: "Hass Hair",
        genero: "unisex",
    },
    {
        id: 5,
        titulo: "Leny Hair",
        iconUrl: "https://assets-global.website-files.com/65a7d1096fb2fb72ed44a291/65ae44d0145b7954f53cbdc2_onda3.png",
        descricao: "P. Wig Futura Lisa Curta Uso Diário Castanho Escuro Tamanho...",
        preco: "98087.21",
        categoria: 'ondulada',
        fullDescricao: "Aparência super natural; sem dor e não parece peruca; Fácil aplicação; touca aberta de 35 cm; Fibra futura; elástico de ajuste; leve e macia; Suporta calor de secador e chapinha até 180 graus c",
        quantidade: 60,
        marca: "Hass Hair",
        genero: "feminino",
    },
    {
        id: 6,
        titulo: "Cabelo Mania",
        iconUrl: "https://assets-global.website-files.com/65a7d1096fb2fb72ed44a291/65ae37de852f80447e78faf7_onda1.png",
        descricao: "P. Wig Futura Lisa Curta Uso Diário Castanho Escuro Tamanho...",
        preco: "23222.12",
        categoria: 'ondulada',
        fullDescricao: "Aparência super natural; sem dor e não parece peruca; Fácil aplicação; touca aberta de 35 cm; Fibra futura; elástico de ajuste; leve e macia; Suporta calor de secador e chapinha até 180 graus c",
        quantidade: 60,
        marca: "Hass Hair",
        genero: "masculino",
    },
    {
        id: 9,
        titulo: "Fashion Line",
        iconUrl: "https://assets-global.website-files.com/65a7d1096fb2fb72ed44a291/65ae4378e483ccd1c13a89fd_onda2.png",
        descricao: "P. Wig Futura Lisa Curta Uso Diário Castanho Escuro Tamanho...",
        preco: "34003.20",
        categoria: 'ondulada',
        fullDescricao: "Aparência super natural; sem dor e não parece peruca; Fácil aplicação; touca aberta de 35 cm; Fibra futura; elástico de ajuste; leve e macia; Suporta calor de secador e chapinha até 180 graus c",
        quantidade: 73,
        marca: "Hass Hair",
        genero: "masculino",
    },

    //Perucas Lisas

    {
        id: 10,
        titulo: "Black Beauty",
        iconUrl: "https://assets-global.website-files.com/65a7d1096fb2fb72ed44a291/65a8f8c190bf40ac00098928_Peruca%20Wig%20Futura%20Lisa%20Curta%20Uso%20Di%C3%A1rio%20Castanho%20Escuro%20%20Com%20Mechas.png",
        descricao: "P. Wig Futura Lisa Curta Uso Diário Castanho Escuro Tamanho...",
        preco: "19987.50",
        categoria: 'lisa',
        fullDescricao: "Aparência super natural; sem dor e não parece peruca; Fácil aplicação; touca aberta de 35 cm; Fibra futura; elástico de ajuste; leve e macia; Suporta calor de secador e chapinha até 180 graus c",
        quantidade: 60,
        marca: "Hass Hair",
        genero: "femenino",
    },
    {
        id: 11,
        titulo: "Black Beauty",
        iconUrl: "https://assets-global.website-files.com/65a7d1096fb2fb72ed44a291/65a8e1c859abffc53d6bc54d_Peruca%20Lace%20Wig%20Cachos%20Frizados%20Longa%20Volumosa.png",
        descricao: "P. Wig Futura Lisa Curta Uso Diário Castanho Escuro Tamanho...",
        preco: "92456.12",
        categoria: 'lisa',
        fullDescricao: "Aparência super natural; sem dor e não parece peruca; Fácil aplicação; touca aberta de 35 cm; Fibra futura; elástico de ajuste; leve e macia; Suporta calor de secador e chapinha até 180 graus c",
        quantidade: 20,
        marca: "Hass Hair",
        genero: "unisexo",
    },
    {
        id: 12,
        titulo: "Cabelo Mania",
        iconUrl: "https://assets-global.website-files.com/65a7d1096fb2fb72ed44a291/65a8f8c190bf40ac00098928_Peruca%20Wig%20Futura%20Lisa%20Curta%20Uso%20Di%C3%A1rio%20Castanho%20Escuro%20%20Com%20Mechas.png",
        descricao: "P. Wig Futura Lisa Curta Uso Diário Castanho Escuro Tamanho...",
        preco: "89387.50",
        categoria: 'lisa',
        fullDescricao: "Aparência super natural; sem dor e não parece peruca; Fácil aplicação; touca aberta de 35 cm; Fibra futura; elástico de ajuste; leve e macia; Suporta calor de secador e chapinha até 180 graus c",
        quantidade: 92,
        marca: "Hass Hair",
        genero: "masculino",
    },
    {
        id: 13,
        titulo: "Fashion Line",
        iconUrl: "https://assets-global.website-files.com/65a7d1096fb2fb72ed44a291/65a8f7f0b1bd343d622dee62_Peruca%20Wig%20Fibra%20Organica%20Kinky%20Curly%20Cacheada%20Longa%20Afro.png",
        descricao: "P. Wig Futura Lisa Curta Uso Diário Castanho Escuro Tamanho...",
        preco: "16456.12",
        categoria: 'lisa',
        fullDescricao: "Aparência super natural; sem dor e não parece peruca; Fácil aplicação; touca aberta de 35 cm; Fibra futura; elástico de ajuste; leve e macia; Suporta calor de secador e chapinha até 180 graus c",
        quantidade: 92,
        marca: "Hass Hair",
        genero: "masculino",
    },

    //Perucas Curtas

    {
        id: 14,
        titulo: "F.Y Hair  - Weng",
        iconUrl: "https://assets-global.website-files.com/65a7d1096fb2fb72ed44a291/65ae34cfbeb57c69fe5cfa1c_cacheada2.png",
        descricao: "P. Wig Futura Lisa Curta Uso Diário Castanho Escuro Tamanho...",
        preco: "54987.50",
        categoria: 'curta',
        fullDescricao: "Aparência super natural; sem dor e não parece peruca; Fácil aplicação; touca aberta de 35 cm; Fibra futura; elástico de ajuste; leve e macia; Suporta calor de secador e chapinha até 180 graus c",
        quantidade: 92,
        marca: "Hass Hair",
        genero: "masculino",
    },
    {
        id: 15,
        titulo: "Cacheado Afro",
        iconUrl: "https://assets-global.website-files.com/65a7d1096fb2fb72ed44a291/65a8fbf8eefa961aea618bf6_Peruca%20De%20Cabelo%20Humano%20Curto%20Cacheado%20Afro%20Promo%C3%A7%C3%A3o.png",
        descricao: "P. Wig Futura Lisa Curta Uso Diário Castanho Escuro Tamanho...",
        preco: "56432.90",
        categoria: 'curta',
        fullDescricao: "Aparência super natural; sem dor e não parece peruca; Fácil aplicação; touca aberta de 35 cm; Fibra futura; elástico de ajuste; leve e macia; Suporta calor de secador e chapinha até 180 graus c",
        quantidade: 92,
        marca: "Hass Hair",
        genero: "femenino",
    },
    {
        id: 16,
        titulo: "Hass Hair",
        iconUrl: "https://assets-global.website-files.com/65a7d1096fb2fb72ed44a291/65ae5fb3aa01b21823c5c6a8_curta2.png",
        descricao: "P. Wig Futura Lisa Curta Uso Diário Castanho Escuro Tamanho...",
        preco: "16887.50",
        categoria: 'curta',
        fullDescricao: "Aparência super natural; sem dor e não parece peruca; Fácil aplicação; touca aberta de 35 cm; Fibra futura; elástico de ajuste; leve e macia; Suporta calor de secador e chapinha até 180 graus c",
        quantidade: 92,
        marca: "Hass Hair",
        genero: "masculino",
    },
    {
        id: 17,
        titulo: "Lace Cacheado Afro",
        iconUrl: "https://assets-global.website-files.com/65a7d1096fb2fb72ed44a291/65ae30b6c404c7659500d8f2_cacheada1.png",
        descricao: "P. Wig Futura Lisa Curta Uso Diário Castanho Escuro Tamanho...",
        preco: "82056.12",
        categoria: 'curta',
        fullDescricao: "Aparência super natural; sem dor e não parece peruca; Fácil aplicação; touca aberta de 35 cm; Fibra futura; elástico de ajuste; leve e macia; Suporta calor de secador e chapinha até 180 graus c",
        quantidade: 92,
        marca: "Hass Hair",
        genero: "unisexo",
    },

    //Perucas Crespas

    {
        id: 18,
        titulo: "Fashion Line",
        iconUrl: "https://assets-global.website-files.com/65a7d1096fb2fb72ed44a291/65ae34cfbeb57c69fe5cfa1c_cacheada2.png",
        descricao: "P. Wig Futura Lisa Curta Uso Diário Castanho Escuro Tamanho...",
        preco: "78987.50",
        categoria: 'ondulada',
        fullDescricao: "Aparência super natural; sem dor e não parece peruca; Fácil aplicação; touca aberta de 35 cm; Fibra futura; elástico de ajuste; leve e macia; Suporta calor de secador e chapinha até 180 graus c",
        quantidade: 92,
        marca: "Hass Hair",
        genero: "unisexo",
    },
    {
        id: 19,
        titulo: "Lace Cacheado Afro",
        iconUrl: "https://assets-global.website-files.com/65a7d1096fb2fb72ed44a291/65ae30b6c404c7659500d8f2_cacheada1.png",
        descricao: "P. Wig Futura Lisa Curta Uso Diário Castanho Escuro Tamanho...",
        preco: "82056.12",
        categoria: 'ondulada',
        fullDescricao: "Aparência super natural; sem dor e não parece peruca; Fácil aplicação; touca aberta de 35 cm; Fibra futura; elástico de ajuste; leve e macia; Suporta calor de secador e chapinha até 180 graus c",
        quantidade: 92,
        marca: "Hass Hair",
        genero: "unisexo",
    },
    {
        id: 20,
        titulo: "Fashion Line",
        iconUrl: "https://assets-global.website-files.com/65a7d1096fb2fb72ed44a291/65ae34cfbeb57c69fe5cfa1c_cacheada2.png",
        descricao: "P. Wig Futura Lisa Curta Uso Diário Castanho Escuro Tamanho...",
        preco: "78987.50",
        categoria: 'ondulada',
        fullDescricao: "Aparência super natural; sem dor e não parece peruca; Fácil aplicação; touca aberta de 35 cm; Fibra futura; elástico de ajuste; leve e macia; Suporta calor de secador e chapinha até 180 graus c",
        quantidade: 92,
        marca: "Hass Hair",
        genero: "unisexo",
    },
    {
        id: 21,
        titulo: "Lace Cacheado Afro",
        iconUrl: "https://assets-global.website-files.com/65a7d1096fb2fb72ed44a291/65ae30b6c404c7659500d8f2_cacheada1.png",
        descricao: "P. Wig Futura Lisa Curta Uso Diário Castanho Escuro Tamanho...",
        preco: "82056.12",
        categoria: 'ondulada',
        fullDescricao: "Aparência super natural; sem dor e não parece peruca; Fácil aplicação; touca aberta de 35 cm; Fibra futura; elástico de ajuste; leve e macia; Suporta calor de secador e chapinha até 180 graus c",
        quantidade: 92,
        marca: "Hass Hair",
        genero: "unisexo",
    },
    {
        id: 22,
        titulo: "Lace Cacheado Afro",
        iconUrl: "https://assets-global.website-files.com/65a7d1096fb2fb72ed44a291/65ae30b6c404c7659500d8f2_cacheada1.png",
        descricao: "P. Wig Futura Lisa Curta Uso Diário Castanho Escuro Tamanho...",
        preco: "82116.12",
        categoria: 'crespa',
        fullDescricao: "Aparência super natural; sem dor e não parece peruca; Fácil aplicação; touca aberta de 35 cm; Fibra futura; elástico de ajuste; leve e macia; Suporta calor de secador e chapinha até 180 graus c",
        quantidade: 17,
        marca: "Wig Fashion",
        genero: "femenino",
    },
    {
        id: 23,
        titulo: "Fashion Line",
        iconUrl: "https://assets-global.website-files.com/65a7d1096fb2fb72ed44a291/65ae34cfbeb57c69fe5cfa1c_cacheada2.png",
        descricao: "P. Wig Futura Lisa Curta Uso Diário Castanho Escuro Tamanho...",
        preco: "78987.50",
        categoria: 'crespa',
        fullDescricao: "Aparência super natural; sem dor e não parece peruca; Fácil aplicação; touca aberta de 35 cm; Fibra futura; elástico de ajuste; leve e macia; Suporta calor de secador e chapinha até 180 graus c",
        quantidade: 12,
        marca: "Hass Fashion Hair",
        genero: "femenino",
    },

];


export function findPerucasById(perucasId:number) {
    return PERUCAS.find(perucas => perucas.id == perucasId);
}
